[env:supermini]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2
    mathertel/OneButton
build_flags =
    ; โหมดทดสอบ: เร่งเวลา 60 เท่า (25 นาที -> 25 วินาที) ลบบรรทัดนี้เมื่อใช้งานจริง
    -D DEBUG_FAST
